# Generated by Django 5.1.7 on 2025-08-21 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gridmodels',
            old_name='derived_option',
            new_name='derivedOption',
        ),
    ]
