# Generated by Django 5.1.7 on 2025-08-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0002_rename_derived_option_gridmodels_derivedoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridmodels',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gridmodels',
            name='derivedOption',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gridmodels',
            name='inputValue',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
