# Generated by Django 5.1.7 on 2025-08-23 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0004_usermodels'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userModels',
        ),
    ]
