# Generated by Django 5.1.7 on 2025-08-23 19:54

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0005_delete_usermodels'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridmodels',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
