# Generated by Django 5.1.7 on 2025-08-23 21:02

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0006_gridmodels_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridmodels',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, null=True),
        ),
    ]
